sudo: false
dist: trusty
language: bash

env:
#- CONDA=https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
- CONDA=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

before_install:
  - curl $CONDA > conda.sh
  - bash conda.sh -b -p $HOME/conda
  - export PATH=$HOME/conda/bin:$PATH
  - conda install --yes -c conda-forge pandoc=2.1.3
  - conda install --yes pyyaml
  - pip install --target=.lib --ignore-installed 'about>=5.1,<6'

install:
  - pip install .

script: 
  - python test.py

