name: pandoc
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandoc=2.9.2
  - plumbum
  - ply
  - pip
  - setuptools
  - wheel
  - twine
  - strictyaml
  - black
  - pip:
    - mkdocs
    - mkdocs-material
