name: pandoc
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandoc=2.11.4
  - plumbum
  - ply
  - pip
  - setuptools
  - wheel
  - twine
  - strictyaml
  - black
  - pip:
    - mkdocs
    - mkdocs-material
