site_name: Pandoc

docs_dir: mkdocs

site_dir: docs

pages:
  - Overview (wip): index.md
  - Examples (wip): examples.md
  - CLI (wip): cli.md
  - Document structure (wip): document.md
  - Elements (wip): elements.md
  - Iteration (wip): iteration.md
  - Configuration: configuration.md
  - Cookbook (wip): cookbook.md
  - API Reference: api.md

theme: "material" 

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

repo_name: "pandoc"
repo_url: "https://github.com/boisgera/pandoc"
edit_uri: edit/master/mkdocs/


