name: main
on: [push]

jobs:
  main:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      # Checkout
      # ------------------------------------------------------------------------
      - uses: actions/checkout@v2

      # Activate Conda Environment
      # ----------------------------------------------------------------------
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pandoc
          environment-file: environment.yml

      # Install and test Python pandoc
      # ------------------------------------------------------------------------
      - run: python setup.py install
      - run: python test.py
